# Site settings
title:       Abhinav Kumar
email:       me@abhinavk.me
author:      Abhinav Kumar
description: ""
baseurl:     ""
url:         "http://abhinavk.me"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: abhinavk
twitter_username: abhinavkmr
google_plus_id: +AbhinavKumar1
linkedin_username: abhinavkumarin
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
