# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /:year/:month/:title/
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Abhinav Kumar
baseurl: # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: 'IAmA. Geek. Programmer. Tolkienian. Redditor. Open-source lover. Suffering from OCD and atheism.'
email: me@abhinavk.me
twitter: abhinavkmr
icon_url: /images/meawe.jpg
disqus_shortname: abhinavkme

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: 
footer_description: 
social_links_title: 
github_url: https://github.com/abhinavk
flickr_url: 
instagram_url: 
vimeo_url: 
facebook_url: https://www.facebook.com/abhinavkmr
google_plus_url: http://plus.google.com/++AbhinavKumar1
pinterest_url: 
tumblr_url: 
linkedin_url: 
dribbble_url: 
lastfm_url: http://www.last.fm/user/ak47x2
rdio_url: 
spotify_url: 
skype_url: 
soundcloud_url: 
behance_url: 
